services:
  mysql:
    image: mysql:8.0
    container_name: zdc-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: config_db
    ports:
      - "33306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7
    container_name: zdc-redis
    ports:
      - "36379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
